name: Triage issue

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/software-mansion/projects/33
          github-token: ${{ secrets.CAIROLS_TRIAGE_GITHUB_TOKEN }}
