on:
  workflow_call: # This makes it callable from other workflows
jobs:
  test-ui-parametrized:
    name: test ui
    strategy:
      matrix:
        scarb: ["latest"]
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Restore Test Resources Cache
        uses: actions/cache/restore@v5
        with:
          path: /tmp/test-resources
          key: test-resources-${{ github.sha }}
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "20.x"
          cache: npm
      - uses: software-mansion/setup-scarb@v1
        if: ${{ matrix.scarb != 'disabled' }}
        with:
          scarb-version: ${{ matrix.scarb }}
      - run: npm ci
      - run: npm run compile-test
      - run: echo "SCARB_VERSION=${{ matrix.scarb }}" >> $GITHUB_ENV
        shell: bash
      - run: |
          sudo apt update
          sudo apt install -y xvfb libnspr4 libnss3 libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0 libgbm1 libasound2t64
      - run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npm run ui-test
        if: ${{ matrix.os == 'ubuntu-24.04'}}
      - run: npm run ui-test
        if: ${{ matrix.os != 'ubuntu-24.04'}}
